---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aks-static
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: aks-static
    spec:
      containers:
      - name: aks-static
        image: adcoutregistry.azurecr.io/aks-static:v1
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: akssecret
---
apiVersion: v1
kind: Service
metadata:
  name: aks-static
spec:
  type: LoadBalancer
  ports:
  - port: 8000
  selector:
    app: aks-static